
services:
  app:
    container_name: route-optima-backend
    image: rockyhaque/route-optima:latest
    build: .
    ports:
      - '3008:3008'
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:prod"

  postgres:
    image: postgres:16-alpine
    container_name: nest-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
